window:
  width: 1280
  height: 720
  title: TowerDefence2
  max_fps: 60

project:
  name: TowerDefence2 # project dirname
  sources: src # source code directory
  maps: maps # maps directory
  logs: logs # logs directory
  font: system # font type

game:
  money:
    easy: 200
    normal: 100
    hard: 50

  managers:
    map:
      field-size-x: 1280
      field-size-y: 640
      road-width: 25 # mb make it less?
      base: # base size and hp (we rly need size here?)
        height: 100
        width: 200
        max_hp: 10 # ToDo: add difficult depend
    enemy:
      wave-size: 10 # ToDo: add wave size depends on enemy type
      # Maybe we need to change enemy spawn rules,
      # for example we can add random count of enemies, but we must
      # calculate new enemies stats (mb smth about max-hp-to-wave)
      time-between-waves: 20 # in seconds
      time-between-enemies: 1 # in seconds
      enemies: #  enemies types
        # colors used only on alpha versions of builds
        - name: default
          speed: 1  # speed divided to x and y speeds
          hp: 100
          hp-mod: 1.10 # hp *= (1 + hp-mod)
          color: green

        - name: forced
          speed: 0.5
          hp: 200
          hp-mod: 1.20
          color: red

        - name: fast
          speed: 2
          hp: 50
          hp-mod: 1.05
          color: blue

    turret:
      turrets:
        - name: gunner
          rate:
            base: 1.3
            step: 0.2
            max: 2.7
            cost: 100
            cost-mod: 1.4
          damage:
            base: 99
            step: 50
            max: 280
            cost: 100
            cost-mod: 1.4
          range:
            base: 100
            step: 20
            max: 180
            cost: 100
            cost-mod: 1.4